---
# tasks file for tomcat
- name: Create Tomcat Deployment Home Dir.
  file: path={{doc_tomcat}} state=directory

- name: Download Tomcat TarBall
  get_url: url={{tomcat_url}} dest={{doc_tomcat}}/tomcat.tar.gz mode=0755
  
- name: Extract Tomcat TarBall
  command: "tar zxf {{doc_tomcat}}/tomcat.tar.gz -C {{doc_tomcat}} --strip-components 1"

- name: Install Java 1.8 JDK
  apt: name=default-jdk state=present

- name: Deploy Petclinic War
  copy: src=files/petclinic.war  dest={{doc_tomcat}}/webapps/ mode=0644

- name: Deploy Jenkins Web Page
  copy: src=files/jenkins.html dest={{doc_root}}/index.html
  notify:
  - Restart Tomcat

- name: Deploy Custom Info web Page
  template: src=templates/info.j2 dest={{doc_root}}/info.html

