---
# Update1 : Getting Prepared for Tomcat Deployment
# Update2 : Deploy Petclinic War 
# Update3 : Bring up the tomcat - Not Working ( Handler Require a Notify ) 
# Update4 : Deploy Web Page with Notify. 
# Update5 : Force the Handler to Run via making changes in Template - by updating admin Varibale : "Tomcat-Deployment-Test-01"
# Update6 : 


- hosts: web:db
  name: Tomcat Deployment 
  vars:
    doc_tomcat: "/opt/SP/apps/tomcat"
    doc_root: "/var/www/html"
    admin: "Tomcat-Deployment-Test-01"
    tomcat_url: "https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.59/bin/apache-tomcat-8.5.59.tar.gz"

  tasks:
  - name: Create Tomcat Deployment Home Dir.
    file: path={{doc_tomcat}} state=directory
  
  - name: Download Tomcat TarBall
    get_url: url="https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.59/bin/apache-tomcat-8.5.59.tar.gz" dest={{doc_tomcat}}/tomcat.tar.gz mode=0755
  
  - name: Extract Tomcat TarBall
    command: "tar zxf {{doc_tomcat}}/tomcat.tar.gz -C {{doc_tomcat}} --strip-components 1"

  - name: Install Java 1.8 JDK
    apt: name=default-jdk state=present

  - name: Deploy Petclinic War
    copy: src=files/petclinic.war  dest={{doc_tomcat}}/webapps/ mode=0644

  - name: Deploy Custom Info web Page
    template: src=templates/info.j2 dest={{doc_root}}/info.html
    notify:
    - Restart Tomcat

  handlers: 
  - name: Restart Tomcat
    shell: "nohup sh {{doc_tomcat}}/bin/catalina.sh start"
